---
name: github-actions-cache-cleaner
on:
  push:
    branches:
      - develop
      - master
  schedule:
    - cron: "0 21 * * *" # 06:00 JST
  workflow_dispatch:
jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: dev-hato/github-actions-cache-cleaner@cf410e6c656a2bc3c75443a3f2dcef385547c12e # v0.0.51
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
