name: pr-copy-ci-sudden-death
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions: {}
jobs:
  # hato-botのCIの差分がpushされたらPRを作成する
  pr-copy-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          path: sudden-death
          ref: ${{ github.sha }}
          persist-credentials: false
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          repository: ${{ github.repository_owner }}/hato-bot
          path: hato-bot
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          cache-dependency-path: sudden-death/package-lock.json
          node-version-file: sudden-death/package.json
      - run: bash "${GITHUB_WORKSPACE}/sudden-death/scripts/pr_copy_ci_sudden_death/pr_copy_ci/npm_ci.sh"
        working-directory: sudden-death
      - name: Copy CI
        run: bash "${GITHUB_WORKSPACE}/sudden-death/scripts/pr_copy_ci_sudden_death/pr_copy_ci/copy_ci.sh"
      - name: Copy package.json
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const {tsImport} = require('tsx/esm/api')
            const {default: {script}} = await tsImport(
              './scripts/pr_copy_ci_sudden_death/pr_copy_ci/copy_package.ts',
              process.env.GITHUB_WORKSPACE + '/sudden-death/'
            )
            script()
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.PROJECT_AUTOMATION_APP_CLIENT_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: dev-hato/actions-diff-pr-management@571be0d9572aaf77cdd315c12d6e73a1112910d7 # v2.2.6
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          branch-name-prefix: pr-copy-ci
          pr-title-prefix: hato-botのCIを反映するよ！
          working-directory: sudden-death
          exit-failure: "false"
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
