name: pr-copy-ci-sudden-death
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions: {}
jobs:
  # hato-botのCIの差分がpushされたらPRを作成する
  pr-copy-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          path: sudden-death
          ref: ${{ github.sha }}
          persist-credentials: false
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          repository: ${{ github.repository_owner }}/hato-bot
          path: hato-bot
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          cache-dependency-path: sudden-death/package-lock.json
          node-version-file: sudden-death/package.json
      - run: bash "${GITHUB_WORKSPACE}/sudden-death/scripts/pr_copy_ci_sudden_death/pr_copy_ci/npm_ci.sh"
        working-directory: sudden-death
      - name: Copy CI
        run: bash "${GITHUB_WORKSPACE}/sudden-death/scripts/pr_copy_ci_sudden_death/pr_copy_ci/copy_ci.sh"
      - name: Copy package.json
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const {tsImport} = require('tsx/esm/api')
            const {default: {script}} = await tsImport(
              './scripts/pr_copy_ci_sudden_death/pr_copy_ci/copy_package.ts',
              process.env.GITHUB_WORKSPACE + '/sudden-death/'
            )
            script()
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: dev-hato/actions-diff-pr-management@5cd3792bc98beed11cda90898bc81af6bfa199af # v2.2.5
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          branch-name-prefix: pr-copy-ci
          pr-title-prefix: hato-botのCIを反映するよ！
          working-directory: sudden-death
          exit-failure: "false"
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
